using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Storage;

[GenerateTypedNameReferences]
public sealed partial class BagOfHoldingConfirmWindow : FancyWindow
{
    public Action? OnConfirmed;
    public Action? OnCancelled;

    public BagOfHoldingConfirmWindow()
    {
        RobustXamlLoader.Load(this);
        YesButton.OnPressed += _ => OnConfirmed?.Invoke();
        NoButton.OnPressed += _ => OnCancelled?.Invoke();
    }
}